openapi: 3.0.0
info:
  title: Admin Management API
  version: 1.0.0
  description: Admin Management API
servers:
  - url: "/api/s1"
    description: local and codespaces

tags:
  - name: admins
    description: admin management s1

paths:
  /admins/login:
    post:
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        "200":
          description: Login successful
          content:
            application/json:
              schema:
                required:
                  - admin_id
                type: object
                properties:
                  admin_id:
                    type: string
        "401":
          description: Invalid credentials. Please try again.
        "423":
          description: >-
            Your account has been blocked due to multiple failed login attempts. Please reset your
            password
  /admins/{id}/deactivate:
    put:
      summary: Deactivate an admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_id:
                  type: string
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Deactivation successful
        "400":
          description: You cannot deactivate your own account.
        "403":
          description: You don't have permission to perform this action.
        "500":
          description: Unable to deactivate the account. Please try again later.
  /admins/{id}/profile:
    put:
      summary: Update admin profile (tester:@Georgy29)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                full_name:
                  type: string
                bio:
                  type: string
                profile_photo:
                  type: string
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Profile updated successfully
        "400":
          description: Invalid input data
        "401":
          description: Unauthorized action
  /admins:
    get:
      summary: Get a list of admins
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "401":
          description: You are not authorized to view this resource
  /admins/status-notifications:
    post:
      summary: Send status notifications to admins (tester:@Georgy29)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                action:
                  type: string
                affected_admin_id:
                  type: string
                changed_by_admin_id:
                  type: string
      responses:
        "200":
          description: Notification sent successfully to all active admins
        "400":
          description: Invalid action type
        "401":
          description: You are not authorized to perform this action
        "422":
          description: Email delivery failed
  /admins/password-reset:
    get:
      tags: 
        - admins
      summary: Validate password reset token (author:@Georgy29)
      parameters:
        - in: query
          name: token
          schema:
            type: string
          required: true
          description: Token to be validated
      responses:
        "200":
          description: Valid token
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessObject"
              examples:
                successExample:
                  summary: Valid token example
                  value:
                    status: "success"
                    messages:
                      - "Token is valid. Proceed with password reset."
                    data:
                      userId: 12345            
                      additionalInfo: "Sample additional data (expirity_date)" 
        "400":
          description: Invalid or expired token.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
              example:
                value:
                  status: "error"
                  errors:
                    - "The provided token is invalid or expired."
                    - "Please request a new password reset."
                  locations:
                    - "admins.controller.js"
                    - "admins.service.js"
                    - "admins.database.js"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
    put:
      tags:
        - admins
      summary: Reset the user's password (with a valid token) (author:@Georgy29)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                new_password:
                  type: string
                  description: The new password to be set for the user
                  minLength: 8
                  maxLength: 64
      responses:
        "200":
          description: Password reset successful.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessObject"
              examples:
                successExample:
                  summary: Success message for successful password reset
                  value:
                    status: "success"
                    messages:
                      - "Password reset successfully."
                      - "You can now log in with your new password."
        "400":
          description: Invalid or expired token, or password does not meet complexity requirements.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
              examples:
                invalidTokenExample:
                  summary: Invalid token example
                  value:
                    status: "error"
                    errors:
                      - "The token provided is invalid or expired."
                      - "Please check the token and try again."
                    locations:
                      - "admins.controller.js"
                      - "admins.service.js"
                complexityErrorExample:
                  summary: Password complexity error example
                  value:
                    status: "error"
                    errors:
                      - "Password does not meet complexity requirements."
                      - "Ensure the password is at least 8 characters long and contains a mix of letters, numbers, and symbols."
                    locations:
                      - "admins.controller.js"
                      - "admins.service.js"
                      - "admins.database.js"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
    post:
      tags: 
        - admins
      summary: Request a password reset link to an email (author:@Georgy29)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: The user's email address for which the password reset is requested.
                  format: email
      responses:
        "200":
          description: Check your email for a password reset link.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SuccessObject"
              examples:
                successExample:
                  summary: Success message for requesting a password reset
                  value:
                    status: "success"
                    messages:
                      - "Check your email for the password reset link."
        "400":
          description: Email address not found or invalid.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"
              examples:
                notFoundExample:
                  summary: Email address not found example
                  value:
                    status: "error"
                    errors:
                      - "The email address provided is not associated with any account."
                    locations:
                      - "admins.controller.js"
                      - "admins.service.js"
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorObject"

  /admin/logs:
    get:
      summary: Get admin logs
      parameters:
        - name: page
          in: query
          schema:
            type: integer
        - name: limit
          in: query
          schema:
            type: integer
        - name: startDate
          in: query
          schema:
            type: string
            format: date
        - name: endDate
          in: query
          schema:
            type: string
            format: date
        - name: user
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
        "401":
          description: You are not authorized to view this resource
        "500":
          description: Unable to retrieve logs. Please try again later.
  /admin/export:
    get:
      summary: Export admin data
      parameters:
        - name: format
          in: query
          required: true
          schema:
            type: string
            enum: [csv]
      responses:
        "200":
          description: Export generated successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  download_url:
                    type: string
        "400":
          description: Invalid export configuration
        "500":
          description: Unable to generate export. Please try again later.
  /admin/import:
    put:
      summary: Import admin data
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: string
              format: binary
      responses:
        "200":
          description: Import successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  summary:
                    type: object
                    properties:
                      total:
                        type: integer
                      successful:
                        type: integer
                      failed:
                        type: integer
        "400":
          description: Invalid file format
          content:
            application/json:
              schema:
                type: object
                properties:
                  errors:
                    type: array
                    items:
                      type: object
                      properties:
                        row:
                          type: integer
                        message:
                          type: string
        "413":
          description: File size exceeds limit
        "500":
          description: Import processing failed
  /admins/register:
    post:
      summary: Register a new admin
      requestBody:
        required: true
        content:
          application/json:
            schema:
              required:
                - email
              type: object
              properties:
                full_name:
                  type: string
                email:
                  type: string
                phone:
                  type: string
                password:
                  type: string
                address:
                  type: string
                activation_code:
                  type: string
                profile_photo:
                  type: string
                bio:
                  type: string
      responses:
        "201":
          description: Registration successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  new_id:
                    type: string
        "400":
          description: >-
            Invalid or expired registration code or Password does not meet complexity
            requirements
        "500":
          description: Unable to register. Please try again later.

components:
  schemas:
    ErrorObject:
      type: object
      properties:
        status:
          type: string
          description: "The status of the error (e.g., 'error')"
        errors:
          type: array
          items:
            type: string
          description: "List of error messages"
          example: ["invalid", "not available"]
        locations:
          type: array
          items:
            type: string
          description: "Optional: Locations where the error occurred (e.g., file names)"
          example: ["db.js", "service.js"]

    SuccessObject:
      type: object
      properties:
        status:
          type: string
          description: "The status of the response (e.g., 'success')"
        locations:
          type: array
          items:
            type: string
          description: "Optional: Tracking locations related to the response data"
          example: ["tracking location optional"]
        messages:
          type: array
          items:
            type: string
          description: "Messages that provide additional context about the response"
          example: ["Tracking location optional"]
        data:                  
          type: object        
          description: "Optional field for additional data related to the response"
          additionalProperties: true  # Allows flexibility in structure(have 1 or more data to output)
          example:
            key1: "value1"
            key2: "value2"