openapi: 3.0.0
info:
  title: Messaging API
  version: 1.0.0
servers:
  - url: "/api/s3"
    description: local and codespaces
paths:
  /messages:
    post:
      summary: "Send a message (author: @Iryna)"
      description: As an admin, I want to send messages to other admins in the system so that I can communicate.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: integer
                thread_id:
                  type: integer
                content:
                  type: string
                time:
                  type: string
      responses:
        "200":
          description: Message sent successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  id:
                    type: integer
                  sender:
                    type: integer
                  content:
                    type: string
        "400":
          description: Input can't be empty
        "500":
          description: Error sending message, please try again later

  /messages/{thread_id}:
    get:
      summary: "Get messages by thread ID (author: @Iryna)"
      description: As an admin, I want to retrieve all messages within a specific thread so that I can view the conversation history with other admins in the system.
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  messages:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        sender:
                          type: integer
                        recipient:
                          type: integer
                        content:
                          type: string
                        time:
                          type: string
              examples:
                successfulResponse:
                  value:
                    success: true
                    messages:
                      - id: "1"
                        sender: "1"
                        recipient: "2"
                        content: "Hello!"
                        time: "2024-11-08T19:18:53Z"
                      - id: "2"
                        sender: "2"
                        recipient: "1"
                        content: "Hi!"
                        time: "2024-11-08T20:15:23Z"
                emptyResponse:
                  value:
                    success: true
                    messages: []
        "404":
          description: No message history found
        "500":
          description: Unable to load messages, please try again later

    delete:
      summary: Delete a message
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Message deleted and email sent
        "404":
          description: Message not found
        "500":
          description: Email failure, try again later

    patch:
      summary: Mark message as important
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                is_important:
                  type: boolean
      responses:
        "200":
          description: Message marked as important
        "404":
          description: Message not found
        "500":
          description: Error updating message, please try again later

  /admins/{id}/status:
    post:
      summary: Update admin availability status
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                availability_status:
                  type: string
      responses:
        "200":
          description: Status updated successfully
        "404":
          description: Admin not found
        "500":
          description: Error updating status, please try again later

  /messages/history/{admin_id}:
    get:
      summary: Get full message history for an admin
      parameters:
        - name: admin_id
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Success
        "404":
          description: No message history found for this admin
        "500":
          description: Unable to load message history, please try again later

  /messages/reply/{thread_id}:
    post:
      summary: Reply to a message in a thread
      parameters:
        - name: thread_id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                sender_id:
                  type: string
                content:
                  type: string
                reply_to_message_id:
                  type: string
      responses:
        "200":
          description: Reply sent successfully
        "404":
          description: Thread or message not found
        "500":
          description: Server Error

  /adminlogs:
    get:
      summary: Retrieve admin logs
      parameters:
        - name: admin_id
          in: query
          schema:
            type: string
        - name: keyword
          in: query
          schema:
            type: string
        - name: date_range
          in: query
          schema:
            type: string
        - name: sort_by
          in: query
          schema:
            type: string
        - name: order
          in: query
          schema:
            type: string
      responses:
        "200":
          description: Logs retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    log_id:
                      type: string
                    details:
                      type: string
              examples:
                array of logs:
                  value:
                    - log_id: some text
                      details: some text
                    - log_id: some text
                      details: some text
        "400":
          description: Invalid query parameters
        "404":
          description: No logs found
        "500":
          description: Server error

    post:
      summary: Log an admin action
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                admin_id:
                  type: string
                action_type:
                  type: string
                message_id:
                  type: string
                action_time:
                  type: string
                details:
                  type: string
      responses:
        "200":
          description: Log created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  log_id:
                    type: string
                  success:
                    type: boolean
        "400":
          description: Missing required fields admin_id or action_type
        "500":
          description: Unable to log admin action due to server error
